# Header
menu:
  Home: /
  Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title: ngtmuzi

# URL of the Home page image
index_cover: https://p1.bqimg.com/4851/7ae3129e66d21068.jpg

# Default post title
default_post_title: 无标题

# set your own favicon
favicon: /favicon.ico

# Social Accounts
acfun_url: http://www.acfun.cn/u/ngtmuzi
bili_url: http://space.bilibili.com/1772234
ytb_url: https://www.youtube.com/channel/UCCWrMEHE94DBUTmhz2eflVg
twitter_url: https://twitter.com/ngtmuzi
twitter_handle:
facebook_url:
github_url: https://github.com/ngtmuzi
rss_url: /rss2.xml
gitlab_url:
linkedin_url:
mailto: